### ISSUE TITLE
SMS Entity Cron

### ISSUE THREAD

**Issue by LiberTang0** [SythilBlade/sythil-odoo-test#9]
I have this Error at every cron:

2016-07-05 04:46:58,883 1000 ERROR xxxxxxxxx openerp.addons.base.ir.ir_cron: Call of self.pool.get('esms.acc$
Traceback (most recent call last):
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/local/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/src/odoo-addons/entity_sms/esms_accounts.py", line 22, in check_all_messages
    self.env[sms_account.account_gateway.gateway_model_name].check_messages(sms_account.id)
  File "/usr/local/src/odoo-addons/entity_sms/twilio/gateway_config.py", line 87, in check_messages
    num_pages = messages_tag[0].attrib['numpages']
  File "lxml.etree.pyx", line 2295, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:59791)
KeyError: 'numpages'

**Comment by SythilBlade** [comment]
Thank you for bringing this to my attention.

I have released a new version which fixes this bug so please give it a try.

Regards
Steven
